#!/bin/bash
# --------------------------------------------------------------------------
# SCRIPT: first_run_build_and_qemu.sh
# 
# Automates the entire embedded Linux build process:
# 1. Builds the custom AArch64 kernel and root filesystem using Buildroot.
# 2. Cross-compiles the out-of-tree driver module using the generated toolchain.
# 3. Updates the root filesystem with the new driver.
# 4. Launches the emulator (QEMU) for testing.
# --------------------------------------------------------------------------

# --- Configuration ---
BUILDROOT_DIR="buildroot"
DRIVER_DIR="custom_device_driver"
DRIVER_MODULE_NAME="divam_cdev"

# Exit immediately if a command exits with a non-zero status
set -e

echo "======================================================="
echo "=== EMBEDDED LINUX PROJECT AUTOMATION STARTING ==="
echo "======================================================="

# --- PART 1: Buildroot (BSP) Compilation ---
echo "--- 1. BUILDING CUSTOM BUILDROOT IMAGE (BSP) ---"

cd "$BUILDROOT_DIR"

# Step 1a: Clean and load configuration (Prevents the 'Nothing to be done' error)
# echo "Cleaning previous build artifacts..."
# make clean > /dev/null 2>&1 # Redirect output to suppress noise
echo "Loading QEMU AArch64 configuration..."
make qemu_aarch64_virt_defconfig

# --- Prep Check ---
# Note: Ensure Python3 is manually selected in menuconfig before first run.
# make menuconfig 
# ---------------------------

# Step 1b: Final Build (This compiles the toolchain, kernel, and initial rootfs)
echo "Starting full Buildroot compilation (This will take a while)..."
# Use '||' to catch failure and exit gracefully
make -j$(nproc) || { echo "ERROR: Buildroot compilation failed! Check dependencies/menuconfig."; exit 1; }

echo "Buildroot image successfully created."

KERNEL_SOURCE_DIR=$(find output/build/ -maxdepth 1 -type d -name "linux-*" | head -n 1)

# Ensure the variable is set and exit if not found
if [ -z "$KERNEL_SOURCE_DIR" ]; then
    echo "ERROR: Kernel source directory (linux-X.Y.Z) not found after build!"
    exit 1
fi

# Extract the version number (e.g., 6.12.47)
KERNEL_VERSION=$(basename "$KERNEL_SOURCE_DIR" | sed 's/linux-//')

# Define the environment variable that the Makefile relies on
# This is the ABSOLUTE path to the kernel source headers.
export BUILDROOT_LINUX_DIR="${PWD}/${KERNEL_SOURCE_DIR}"

echo "Detected Kernel Version: ${KERNEL_VERSION}"
echo "Exported BUILDROOT_LINUX_DIR: ${BUILDROOT_LINUX_DIR}"

cd .. # Back to top-level directory
# --- END NEW PATH RESOLUTION AND EXPORT ---


# --- PART 2: Driver Cross-Compilation and Rootfs Integration ---
echo "--- 2. CROSS-COMPILING OUT-OF-TREE DRIVER (.ko) ---"

# Step 2a: Compile the driver using the Buildroot-generated environment
cd "$DRIVER_DIR"
echo "Compiling ${DRIVER_MODULE_NAME}.c using cross-compiler..."
make all || { echo "ERROR: Driver compilation failed! Check Makefile paths/syntax."; exit 1; }
echo "Driver module successfully cross-compiled: ${DRIVER_MODULE_NAME}.ko"

# Step 2b: Copy the compiled module to the root filesystem path
# Get the kernel version dynamically from the stamp file
KERNEL_VERSION=$(cat ../buildroot/output/build/linux/.stamp_version)
MODULE_INSTALL_PATH="../buildroot/output/target/lib/modules/${KERNEL_VERSION}/extra/"

echo "Installing module into: ${MODULE_INSTALL_PATH}"
mkdir -p "$MODULE_INSTALL_PATH"
cp "${DRIVER_MODULE_NAME}.ko" "$MODULE_INSTALL_PATH"

cd .. # Back to divam_custom_linux_build/

# Step 2c: Rebuild the rootfs image to include the new module
# This is required to put the module into the final .ext4 disk image
echo "Updating root filesystem image to include the driver..."
cd "$BUILDROOT_DIR"
make rootfs-ext4 || { echo "ERROR: Rootfs image update failed!"; exit 1; }
cd .. # Back to divam_custom_linux_build/

echo "Root filesystem image updated with the driver."


# --- PART 3: Launch QEMU and Test ---
echo "--- 3. LAUNCHING QEMU AND TESTING DRIVER ---"

# The start-qemu.sh script is generated by Buildroot in the images folder
QEMU_LAUNCH_SCRIPT="./buildroot/output/images/start-qemu.sh"

echo "Launching QEMU (login is 'root')..."
echo "---"
echo "NOTE: Use Ctrl+A, then X to quit QEMU when done."
echo "---"

# Launch QEMU with the generated image
"$QEMU_LAUNCH_SCRIPT" -nographic # Use -nographic to run in the current terminal

# --- PART 4: Manual Test Steps Reminder ---
echo "======================================================="
echo "=== MANUAL TEST STEPS IN QEMU CONSOLE ==="
echo "======================================================="
echo "KERNEL VERSION: ${KERNEL_VERSION}"
echo " "
echo "1. Verify driver module exists:"
echo "   ls /lib/modules/${KERNEL_VERSION}/extra/${DRIVER_MODULE_NAME}.ko"
echo " "
echo "2. Load the driver into the running kernel:"
echo "   insmod /lib/modules/${KERNEL_VERSION}/extra/${DRIVER_MODULE_NAME}.ko"
echo "   dmesg | grep divam_custom_gpio # Verify 'Module loaded.' message"
echo " "
echo "3. Create the device node (uses awk to find the dynamic Major Number):"
echo "   mknod /dev/divam_custom_gpio c \$(cat /proc/devices | grep divam_custom_gpio | awk '{print \$1}') 0"
echo " "
echo "4. Test the WRITE operation (User Space -> Kernel Space):"
echo "   echo "SUCCESS" > /dev/divam_custom_gpio"
echo "   dmesg | grep divam_custom_gpio # Should show: Wrote X bytes. Data: SUCCESS"
echo " "
echo "5. Test the READ operation (Kernel Space -> User Space):"
echo "   cat /dev/divam_custom_gpio"
echo "   # Should output: Hello from the custom kernel driver!"
echo " "
echo "6. Unload the driver:"
echo "   rmmod ${DRIVER_MODULE_NAME}"
echo " "
echo "Script finished."
